version: '3.8'

services:
  db:
    image: mysql:5.7
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 5577azcD@$
      MYSQL_DATABASE: magiluc_db
      MYSQL_USER: magiluc_userlgomesroc
      MYSQL_PASSWORD: magiluc_password12345
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - magiluc-network
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "256M"
        reservations:
          cpus: "0.25"
          memory: "128M"

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 5577azcD@$
    networks:
      - magiluc-network

  backend:
    build:
      context: ./magiluc-backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./magiluc-backend:/var/www/html
    depends_on:
      - db
    networks:
      - magiluc-network
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "256M"
        reservations:
          cpus: "0.25"
          memory: "128M"

  frontend:
    build:
      context: ./magiluc-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    volumes:
      - ./magiluc-frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - magiluc-network
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "256M"
        reservations:
          cpus: "0.25"
          memory: "128M"

volumes:
  db_data:

networks:
  magiluc-network:
    driver: bridge
