version: '3.8'

services:
  db:
    image: mysql:5.7
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - magiluc-network

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      PMA_HOST: ${PMA_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - magiluc-network

  backend:
    build:
      context: ./magiluc-backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./magiluc-backend:/var/www/html
    depends_on:
      - db
    networks:
      - magiluc-network

  frontend:
    build:
      context: ./magiluc-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    volumes:
      - ./magiluc-frontend:/app
    depends_on:
      - backend
    networks:
      - magiluc-network

volumes:
  db_data:

networks:
  magiluc-network:
    driver: bridge
